### ISSUE TITLE
Package minted Error: minted v3+ executable is not installed or is not added to PATH.

### ISSUE THREAD

**Issue by projetmbc** [gpoore/minted#401]
The following code doesn't compile.

~~~latex
\documentclass[12pt]{article}

\usepackage{minted}

\begin{document}

\begin{minted}{ruby} 
class Foo
    def init
        pi = Math::PI
        @var = "Pi = #{pi}..."
    end 
end
\end{minted}

\end{document}
~~~

But I can do :

~~~terminal
> python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:45:13) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import latexminted
>>> quit()

> which python
/Users/XXXX/opt/anaconda3/bin/python
~~~

**Comment by gpoore** [comment]
Did you just update using CTAN? I believe that there was an issue with the way that CTAN packaged the files for the new release, and they are in the process of fixing it. As a quick fix for the moment, you can probably `\usepackage{minted2}`, which will use v2.9.

**Comment by projetmbc** [comment]
Yes I have just updated today.

**Comment by gpoore** [comment]
@yves-chevallier Can you post a complete log? When you `pip install latexminted`, is that successfully creating a `latexminted` executable on PATH? Right now, `tlmgr install minted` isn't working for the Python side of things because it omits the Python libraries and doesn't configure a Python executable.

**Comment by muzimuzhi** [comment]
Tested on macOS 14.6.1, I can confirm that `pip3 install --break-system-packages latexminted` did create a `latexminted` executable in `/usr/local/bin`, which is contained in `PATH`.

**Comment by yves-chevallier** [comment]
> ```
> \documentclass{article}
> \usepackage{fontspec}
> \usepackage{minted}
> 
> \begin{document}
> 
> \begin{minted}{python}
> def foo():
>     return 1
> \end{minted}
> 
> \end{document}
> ```

```
/workspace # tlmgr install minted upquote lineno
tlmgr: package repository https://texlive.info/CTAN/systems/texlive/tlnet (verified)
[1/13, ??:??/??:??] install: catchfile [3k]
[2/13, 00:00/00:00] install: etoolbox [9k]
[3/13, 00:00/00:00] install: fancyvrb [12k]
[4/13, 00:00/00:00] install: float [3k]
[5/13, 00:00/00:00] install: fp [19k]
[6/13, 00:00/00:00] install: fvextra [15k]
[7/13, 00:01/00:34] install: latex2pydata [4k]
[8/13, 00:01/00:32] install: minted.x86_64-linuxmusl [1k]
[9/13, 00:01/00:32] install: minted [1237k]
[10/13, 00:01/00:01] install: newfloat [7k]
[11/13, 00:01/00:01] install: pgf [701k]
[12/13, 00:02/00:02] install: pgfopts [2k]
[13/13, 00:02/00:02] install: xcolor [18k]
running mktexlsr ...
done running mktexlsr.
tlmgr: package log updated: /opt/texlive/texmf-var/web2c/tlmgr.log
tlmgr: command log updated: /opt/texlive/texmf-var/web2c/tlmgr-commands.log

/workspace # ls /opt/texlive/texmf-dist/tex/latex/minted/minted
minted.sty   minted1.sty  minted2.sty

/workspace # find /opt/texlive/ -iname '*minted*'
/opt/texlive/texmf-dist/scripts/minted
/opt/texlive/texmf-dist/scripts/minted/latexminted-0.1.0-py3-none-any.whl
/opt/texlive/texmf-dist/scripts/minted/latexminted.py
/opt/texlive/texmf-dist/tex/latex/minted
/opt/texlive/texmf-dist/tex/latex/minted/minted2.sty
/opt/texlive/texmf-dist/tex/latex/minted/minted1.sty
/opt/texlive/texmf-dist/tex/latex/minted/minted.sty
/opt/texlive/bin/x86_64-linuxmusl/latexminted
/opt/texlive/tlpkg/tlpobj/minted.tlpobj
/opt/texlive/tlpkg/tlpobj/minted.x86_64-linuxmusl.tlpobj

/workspace # which latexminted
/opt/texlive/bin/x86_64-linuxmusl/latexminted
/workspace # 

/workspace # ls /opt/texlive/texmf-dist/scripts/minted
latex2pydata-0.4.0-py3-none-any.whl     latexminted.py                          pygments-2.18.0-py3-none-any.whl
latexminted-0.1.0-py3-none-any.whl      latexrestricted-0.4.0-py3-none-any.whl

/workspace # latexminted --version
latexminted 0.1.0 (libraries: latex2pydata 0.4.0, pygments 2.18.0)
```

**Comment by yves-chevallier** [comment]
> Did you just update using CTAN? I believe that there was an issue with the way that CTAN packaged the files for the new release, and they are in the process of fixing it. As a quick fix for the moment, you can probably `\usepackage{minted2}`, which will use v2.9.

Using `\usepackage{minted2}` does not work in the case of other packages that require minted. `tcolorbox` for instance has a `RequirePackage{minted}`

**Comment by projetmbc** [comment]
Maybe some testing using `l3build` should be done in such situation breaking API.

**Comment by projetmbc** [comment]
> Tested on macOS 14.6.1, I can confirm that `pip3 install --break-system-packages latexminted` (I have python3 installed by Homebrew) did create a `latexminted` executable in `/usr/local/bin`, which is contained in `PATH`.
> 
> And after manually installing `latex2pydata`, the example given in [#401 (comment)](https://github.com/gpoore/minted/issues/401#issue-2545776012) compiles for me.

The problem is that I've created a package that needs `minted`. At the moment, my package is broken. This isn't a problem, as I must be the only person to use this package, but it's more problematic in the case of `tcolorbox`.

**Comment by muzimuzhi** [comment]
> Using `\usepackage{minted2}` does not work in the case of other packages that require minted. `tcolorbox` for instance has a `RequirePackage{minted}`

It should work fine if `minted2` is loaded _before_ any `\RequirePackage{minted}`. See https://github.com/T-F-S/tcolorbox/issues/2#issuecomment-2310708161 for more info.
```tex
\documentclass{article}
\usepackage{minted2}
\usepackage{minted}

\begin{document}
\UseName{ver@minted.sty} % "2023/12/18 v2.9"
\end{document}
```

**Comment by projetmbc** [comment]
Thanks a lot for this fix for `tcolorbox`. I will update my only-one-user CTAN package soon. :-)

~~~
\RequirePackage{minted2}

\RequirePackage{tcolorbox}%
               [2024/07/10]

\tcbuselibrary{minted, breakable, skins}
~~~

**Comment by muzimuzhi** [comment]
The trick described in my last comment https://github.com/gpoore/minted/issues/401#issuecomment-2373422277 works for all existing documents in which `minted` were loaded by one of `\usepackage`, `\RequirePackage`, and `\RequirePackageWithOptions`, not just the `tcolorbox` case. And it's provided by `minted`.

But there's a limitation: `minted` options set by `\PassOptionsToPackage{<option list>}{minted}` is not used by `\usepackage{minted2}`. For example try with `\PassOptionsToPackage{draft}{minted}`.

**Comment by gpoore** [comment]
CTAN has repackaged `minted`, so `tlmgr install minted` should now work correctly and install the Python executable with libraries. (It might still be a few hours before the changes get to all servers, but it worked for me several hours ago, and then again just now.) I suppose it might be good to do `tlmgr uninstall minted` first. Also, TeX Live has now added `latexminted` to the trusted executable list, so `-shell-escape` is no longer required.

**Comment by projetmbc** [comment]
This almost works but the first compilation raise one error. No extra file exists at the time of the first compilation...

~~~
./listing-direct.tex:118: Package minted Error: 
 => ./listing-direct:56: Cannot find the correct input file "listing-direct.lis
ting"; there may be multiple files with the same name, or the file may have bee
n modified during compilation.
~~~

**Comment by gpoore** [comment]
@projetmbc To avoid that error, you probably need `\usepackage[highlightmode=immediate]{minted}`. Version 3 attempts to speed up highlighting by performing all highlighting at the very end of a file when a file is compiled for the very first time, and then switches to highlighting immediately on subsequent compiles. But that doesn't work when temp files are being highlighted, since they keep getting modified or deleted during compilation. I may need to modify the optimization process to try to detect things like `tcolorbox` temp files.

**Comment by lstngr** [comment]
I got this error on Leap 15.6 today. It turns out that the Python interpreter is quite old (3.6) and while latexminted is in my PATH, it fails to execute. (One can work around it with a venv since latexminted relies on /usr/bin/env to find the python3 executable).

**Comment by muzimuzhi** [comment]
FYI, from its config and doc, `latexminted` v0.1.0 requires Python 3.8 or newer.

<details><summary>Source snippets</summary>
<p>

https://github.com/gpoore/minted/blob/5a34685c7a0b20cdcd914be3ef0fc8d36d3d13fb/python/pyproject.toml#L9
https://github.com/gpoore/minted/blob/5a34685c7a0b20cdcd914be3ef0fc8d36d3d13fb/latex/RESTRICTED_SHELL_ESCAPE.md?plain=1#L77-L81

</p>
</details>

**Comment by lstngr** [comment]
Thanks @muzimuzhi, indeed. I was mostly making the (unclear, I realize!) point that the error doesn't pinpoint the failure correctly and might be confusing to some users. Cheers!

**Comment by projetmbc** [comment]
The last version works fine. Is it easy to explain the fixes done?

**Comment by gpoore** [comment]
@projetmbc The issues were probably due to #405. Basically, under some configurations, the timestamps and perhaps some other data sent from Python back to LaTeX needed `\detokenize` to guarantee that they were processed correctly.

**Comment by gpoore** [comment]
@yves-chevallier Are you still having any issues, using the latest `minted` v3.1.2 plus `latexminted` v0.2.0? I believe things are now working for everyone else who commented on this issue.

**Comment by HolgerHuo** [comment]
Hi! I'm also facing this issue when building a texlive docker image for overleaf. Currently we install package minted in this way:
```bash
mkdir /install-tl-unx \
&&  wget --quiet https://tug.org/texlive/files/texlive.asc \
&&  gpg --import texlive.asc \
&&  rm texlive.asc \
&&  wget --quiet ${TEXLIVE_MIRROR}/install-tl-unx.tar.gz \
&&  wget --quiet ${TEXLIVE_MIRROR}/install-tl-unx.tar.gz.sha512 \
&&  wget --quiet ${TEXLIVE_MIRROR}/install-tl-unx.tar.gz.sha512.asc \
&&  gpg --verify install-tl-unx.tar.gz.sha512.asc \
&&  sha512sum -c install-tl-unx.tar.gz.sha512 \
&&  tar -xz -C /install-tl-unx --strip-components=1 -f install-tl-unx.tar.gz \
&&  rm install-tl-unx.tar.gz* \
&&  echo "tlpdbopt_autobackup 0" >> /install-tl-unx/texlive.profile \
&&  echo "tlpdbopt_install_docfiles 0" >> /install-tl-unx/texlive.profile \
&&  echo "tlpdbopt_install_srcfiles 0" >> /install-tl-unx/texlive.profile \
&&  echo "selected_scheme scheme-full" >> /install-tl-unx/texlive.profile \
&&  echo "tlpdbopt_sys_bin /usr/bin" >> /install-tl-unx/texlive.profile \
    \
&&  /install-tl-unx/install-tl \
      -profile /install-tl-unx/texlive.profile \
      -repository ${TEXLIVE_MIRROR} \
    \
&&  $(find /usr/local/texlive -name tlmgr) path add \
&&  rm -rf /install-tl-unx
```
And when compiling, it shows: 
```
Package minted Error: minted v3+ executable is not installed or is not added to PATH.
```

I can confirm that python, python3, pygmentize, latexminted are all in my path, and i have python3 > 3.11, latexminted==2.11 (lower than latest, but upgrading doesnt help), and minted from ctan = 3.1.2. 

I seem to have run out of ways to debug.

**Comment by gpoore** [comment]
@HolgerHuo You might try compiling a simple document like this, using the new `debug` package option:
```
\documentclass{article}
\usepackage[debug]{minted}
\begin{document}

X\mintinline{python}{"x"}X

\end{document}
```
If there is some sort of unexpected, uncaught error, it might appear in the `*.minted` temp files that are kept with `debug`, especially if there is an `*.errlog.minted` file. If you don't see something obvious in the `*.minted` files, you could post them here so I can take a look.

At this point, I believe that the issues that others initially had with Docker images with `minted` v3.0.0 have been resolved, so it's possible this is something new or different.

**Comment by HolgerHuo** [comment]
@gpoore The output shows `latexminted.err.LatexMintedConfigError: Permission error prevented access to config file "/tmp/.latexminted_config"` and it seems to be a permission issue on my side. I'll try fix it. Thank you so much for your great help!

**Comment by andreondra** [comment]
It still does not work in Overleaf Community. I opened an issue there, it is probably caused by something specific in the Docker installation.

**Comment by gpoore** [comment]
@andreondra When tlmgr updates the `minted` package, that should include the latest version of `latexminted` and all other Python libraries, installing them within TeX Live. Does Overleaf Community use packages directly from CTAN, or is some sort of intermediate package repository involved, which might cause a time delay in getting the latest packages?

In most cases, upgrading `latexminted` manually should work, but that may occasionally cause errors if the LaTeX side of things gets too far behind the Python side. This is also part of the reason for bundling everything in TeX Live.

**Comment by andreondra** [comment]
I think it uses standard TeXLive installation. I am able to install/update packages via tlmgr and see the minted is the latest version. I'd say that the problem is something with incorrect PATH, because I can actually see latexminted installed in the TeXLive directory, but the system one takes precedence. I'll keep the manually upgraded latexminted for now and see if someone responds in the Overleaf repo.

Thank you for now!

**Comment by HolgerHuo** [comment]
@andreondra Hi, I'm also having this issue with overleaf's sharelatex-base image. From my observations, this issues is due to insufficient access to `/tmp` directory. I haven't figured out how to solve it though.

**Comment by gpoore** [comment]
@HolgerHuo `latexminted` looks for `.latexminted_config` config files in HOME (from Python's `pathlib.Path.home()`), TEXMFHOME (from `kpsewhich`), and the current working directory. These should all be readable locations. However, it looks like one of these corresponds to an unreadable `/tmp` in the image you are working with. That may be an issue with the image configuration. I may also need to consider modifying `latexminted` so that it ignores permission errors in locating the config files.

**Comment by HolgerHuo** [comment]
@gpoore Wow, thanks a lot for providing that information. Overleaf do passes HOME=/tmp environment into the container, so latexminted does need to read/write files into that directory. I just haven't figured out why it doesn't have access to `/tmp`, considering it is just a tmp directory.

**Comment by andrew-selvia** [comment]
I'm afraid I'm encountering the same issue:
```
Package minted Error: minted v3+ executable is not installed, is not added to PATH, or is not permitted with restricted shell escape.
```

I've installed `latexminted`:
```shell
pip install latexminted --break-system-packages
```

`latexminted --version` output:
```
% latexminted --version
latexminted 0.2.0
Python executable for the LaTeX minted package
Libraries: latex2pydata 0.4.0, latexrestricted 0.5.0, pygments 2.18.0
Repository: https://github.com/gpoore/minted
CTAN: https://ctan.org/pkg/minted
PyPI: https://pypi.org/project/latexminted
```

I also installed the `minted` package via MiKTeX:
```
% mpm --list-package-names | grep minted
minted
minted__doc
minted__source
```

I'm compiling my document with `pdflatex` on macOS 15.0.1 (Sequoia). The document did not use minted previously; I just discovered it and am trying to integrate it. The document compiles successfully without the minted portion. I've started with the same bare-bones example shared in the initial post.

Assuming I haven't missed anything obvious, what else should I provide to help debug further?

**Comment by muzimuzhi** [comment]
@andrew-selvia The first part of your problems looks like a MiKTeX issue, see https://github.com/MiKTeX/miktex/issues/1538#issuecomment-2440097231. Sorry I have no idea about the second part.

**Comment by gpoore** [comment]
@andrew-selvia Do you have a `kpsewhich` executable as part of your MiKTeX installation, and if so is it on PATH? If for some reason MiKTeX isn't including its own `kpsewhich` executable under macOS (and perhaps some other operating system), then I will need to rewrite parts of `latexrestricted` that rely on `kpsewhich`.

**Comment by andrew-selvia** [comment]
@gpoore They appear to be present on the PATH:
```
% which kpsewhich
~/bin/kpsewhich
% which initexmf
~/bin/initexmf
% which miktex
~/bin/miktex
```

I did briefly attempt to drill into `latexrestricted` but made no meaningful headway. Anything else you'd like me to provide?

**Comment by gpoore** [comment]
@andrew-selvia Under macOS, `kpsewhich` is apparently a symlink to `miktex-kpsewhich`. I've just released `latexrestricted` v0.6.0, which adds support for `miktex-kpsewhich`. If you upgrade `latexrestricted` with `pip`, that should fix things.

**Comment by andrew-selvia** [comment]
@gpoore It does resolve the first issue:
```
runsystem(latexminted config  --timestamp 20241030113915 FAD58DE7366495DB4650CF
EFAC2FCD61)...**executed**.
```

The document continues to report errors upon compilation, unfortunately.

I have tried running that command manually, but it results in a new error:
```
% latexminted config  --timestamp 20241030113915 FAD58DE7366495DB4650CF
EFAC2FCD61
latexrestricted.err.LatexConfigError: Environment variable SELFAUTOLOC is expected for TeX Live, but was not set
```

**Comment by gpoore** [comment]
@andrew-selvia Go ahead and create a new issue...this is probably no longer related to the original one. If you can post a compilation log and any `.errlog.minted` file, that would be helpful. `latexminted` can only be run manually if you set the expected environment variables; for MiKTeX, that means setting TEXSYSTEM to "miktex".
